namespace TooLazyForGenerators.Sample;

public sealed class SampleOutput : ISourceOutput
{
    public Task GetSource(ISourceOutputContext ctx)
    {
        ctx.AddSource("""
        /// <auto-generated />
        """, "Foo.g.cs");

        return Task.CompletedTask;
    }
}
